apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-and-placement-setup
  namespace: policies
  annotations:
    policy.open-cluster-management.io/controls: PolicyPlacement
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-configure-managed-clustersets-prod-ns
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: ManagedClusterSet
                metadata:
                  name: clusterset1  
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-gitops-cluster-prod-ns
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1alpha1
                kind: ManagedClusterSetBinding
                metadata:
                  name: clusterset1
                  namespace: policies
                spec:
                  clusterSet: clusterset1
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-gitops-placement-1
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1alpha1
                kind: Placement
                metadata:
                  name: placementpolicies
                  namespace: policies
                spec:
                  clusterSets:
                    - clusterset1
                  predicates:
                    - requiredClusterSelector:
                        labelSelector:
                          matchExpressions:
                            - key: environment
                              operator: In
                              values:
                                - dev
