apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: placement-test-policy
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policies.ibm.com/v1alpha1
        kind: TrustedContainerPolicy
        metadata:
          name: placement-test-policy-trustedcontainerpolicy
        spec:
          severity: low
          namespaceSelector:
            include: ["default"]
            exclude: ["kube-system"]
          remediationAction: inform
          imageRegistry: quay.io
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-test-policy-pb
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: placement-test-policy-plr
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: placement-test-policy
---
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: placement-test-policy-plr
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions: []
